name: Proposal Reviewers Check

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  pull_request_target:
    branches:    
      - 'tutorials/**'
  

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      package: ${{ steps.filter.outputs.package }}

    steps:
    - uses: actions/checkout@v2
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          package:
            - 'tutorials/**'

  echo_event:
    runs-on: ubuntu-latest
    steps:
      - run: echo "event ${{ github.event }}"

  request_reviewers:
    name: Request reviews on opened PRs
    steps:
      - name: Create PR review request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.pull_request.html_url }} \
              --add-reviewer @necmttn 

  approved:
    if: ${{ needs.changes.outputs.package == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved" 
      - run: echo ${{ github.event.review.user.login }} approved this PR
      - run: echo ${{ github.event.review.state}} review state 
      - run: echo ${{ github.event.review.author_association}} author_association
      - run: echo ${{ github.event.sender.login}} sender username 

  dismissed:
    if: ${{ needs.changes.outputs.package == 'true' }}
    runs-on: ubuntu-latest
    steps: 
      - run: echo "This PR was dismissed"
      - run: echo ${{ github.event.review.user.login }} dismissed this PR
      - run: echo ${{ github.event.review.state}} review state 
      - run: echo ${{ github.event.review.author_association}} author_association
      - run: echo ${{ github.event.sender.login}} sender username 
